export const profile = {
  name: "Xinyi Lu",
  role: "AI Engineer",
  location: "Singapore",
  headline: "Building production LLM agents that save teams thousands of hours",
  email: "xinyilu2000@gmail.com",
  linkedin: "https://www.linkedin.com/in/xinyi-lu-35b72917a/",
  github: "https://github.com/cl-xy",
};

export const metrics = [
  { value: "7,000", label: "hrs/year saved", context: "Citi policy agents" },
  { value: "4", label: "systems deployed", context: "production" },
  { value: "3", label: "agent debate", context: "bull/bear/moderator" },
  { value: "~20%", label: "efficiency gain", context: "code migration" },
];

export const projects = [
  {
    id: "citi-rag",
    title: "LLM Policy Retrieval Agents",
    subtitle: "Production RAG at Citi saving 7,000 hours/year",
    region: "production-ridge",
    elevation: 4,
    stack: ["Python", "LangChain", "RAG", "FastAPI", "PostgreSQL", "TruLens"],
    objective: "Build LLM agents assisting users with policy retrieval across Citi's Private Bank, replacing manual search across thousands of documents.",
    outcome: "Estimated 7,000 hours/year of manual effort eliminated. Deployed internally to compliance and operations teams.",
    failures: ["rag-eval-lies", "chunking-cross-refs"],
    links: {},
  },
  {
    id: "ai-investment-analyst",
    title: "AI Investment Analyst",
    subtitle: "Agentic stock analysis with 3-agent debate",
    region: "agentic-loop",
    elevation: 3,
    stack: ["LangGraph", "FastMCP", "FastAPI", "React", "SSE", "Fly.io", "Neon"],
    objective: "Build a full-stack AI system orchestrating multiple LLM agents to produce bull/bear investment analyses with live streaming traces.",
    outcome: "End-to-end deployed: Fly.io backend + Vercel frontend + Neon Postgres. 3-agent debate architecture running live.",
    failures: ["sse-silent-drop", "yfinance-none", "openrouter-429"],
    links: { live: "https://ai-investment-analyst-iota.vercel.app", github: "https://github.com/cl-xy/ai-investment-analyst" },
  },
  {
    id: "sas-pyspark",
    title: "SAS-to-PySpark Converter",
    subtitle: "LLM-powered legacy code migration",
    region: "migration-pass",
    elevation: 2,
    stack: ["Python", "FastAPI", "React", "GenAI"],
    objective: "Build a web application automating conversion of SAS codes to PySpark, enhancing migration efficiency for analytics teams.",
    outcome: "~20% efficiency improvement in code migration workflows. Used by data engineering teams.",
    failures: ["sas-edge-cases"],
    links: {},
  },
  {
    id: "decarbonization",
    title: "Portfolio Decarbonization Analysis",
    subtitle: "NLP research on climate finance in Asia",
    region: "research-basin",
    elevation: 1,
    stack: ["Python", "NLP", "scikit-learn", "NLTK", "Pandas"],
    objective: "Analyze decarbonization strategies across Asian financial institutions using NLP on corporate disclosures.",
    outcome: "NUS capstone project, earned Distinction. Analyzed disclosure patterns across major Asian financial institutions.",
    failures: ["boilerplate-signal"],
    links: { github: "https://github.com/cl-xy/bt4103_esg" },
  },
];

export const failures = [
  {
    id: "sse-silent-drop",
    title: "SSE Silent Drop",
    severity: "critical",
    symptom: "Connections dying after 30s through corporate proxies. No error, no timeout, just silence.",
    rootCause: "Proxy buffering small payloads, flushing only on disconnect.",
    fix: "15-second heartbeat pings louder than the buffer timeout.",
    lesson: "Streaming through infrastructure you don't control means you need a keepalive louder than the buffer timeout.",
    project: "ai-investment-analyst",
  },
  {
    id: "yfinance-none",
    title: "yfinance Silent None",
    severity: "high",
    symptom: "Analysis completing with nonsensical output. No error raised, no missing data flag.",
    rootCause: "Library swallows API failures, returns None silently for any field.",
    fix: "Explicit None checks on every field, populated a data_gaps array, surfaced it in the final report.",
    lesson: "Never trust external APIs to fail loudly. Defensive parsing is not optional.",
    project: "ai-investment-analyst",
  },
  {
    id: "openrouter-429",
    title: "OpenRouter 429 Cascades",
    severity: "medium",
    symptom: "Third tool call in a chain would 429, killing the entire analysis run.",
    rootCause: "20 req/min limit hit on 3rd tool call, no retry logic.",
    fix: "Per-ticker Postgres cache with stale-while-revalidate. Most repeat analyses hit zero API calls.",
    lesson: "Rate limits teach you caching architecture faster than any tutorial.",
    project: "ai-investment-analyst",
  },
  {
    id: "rag-eval-lies",
    title: "RAG Eval Lies",
    severity: "high",
    symptom: "TruLens scores showed 0.9+ faithfulness, but users complained answers were technically correct but useless.",
    rootCause: "Measuring retrieval quality, not task completion.",
    fix: "Added task-completion metric: did the user stop searching after getting the agent's answer?",
    lesson: "RAG evaluation is a lie if it only measures retrieval. Measure whether the human stopped searching.",
    project: "citi-rag",
  },
  {
    id: "chunking-cross-refs",
    title: "Chunking Cross-References",
    severity: "medium",
    symptom: "Chunks contained 'see Section 4.2' with no context. Retrieval returned dangling pointers.",
    rootCause: "Standard chunking breaks on policy documents with nested cross-references.",
    fix: "Semantic boundaries with cross-reference expansion. Each chunk carries its dependency context.",
    lesson: "Enterprise documents aren't blog posts. Chunking strategy IS the entire RAG system.",
    project: "citi-rag",
  },
  {
    id: "sas-edge-cases",
    title: "SAS Silent Semantic Errors",
    severity: "high",
    symptom: "Generated code ran without errors but produced different numerical results. Off by fractions of pennies.",
    rootCause: "LLMs producing syntactically valid but semantically wrong PySpark.",
    fix: "Validation layer running both outputs on test datasets, flagging divergence. Caught ~40% of silent failures.",
    lesson: "Code generation without execution-based validation is just sophisticated copy-paste.",
    project: "sas-pyspark",
  },
  {
    id: "boilerplate-signal",
    title: "Corporate Boilerplate",
    severity: "low",
    symptom: "Initial keyword extraction returned near-identical strategies across all institutions.",
    rootCause: "Corporate climate disclosures are 80% boilerplate.",
    fix: "Built a boilerplate detector trained on common phrases, then extracted only the residual signal.",
    lesson: "Signal extraction in corporate text means subtracting the template first.",
    project: "decarbonization",
  },
];

export const personal = {
  tagline: "Outside work, I hike around Singapore and Southeast Asia, practice yoga, and volunteer with youth and elderly communities.",
  photos: [
    { src: "/gallery/img3.jpg", caption: "Grand Canyon, AZ" },
    { src: "/gallery/img2.jpg", caption: "Outdoors" },
    { src: "/gallery/img4.jpg", caption: "Community event, Singapore" },
  ],
};

export const regions = [
  { id: "basecamp", label: "Basecamp", x: 50, y: 52, type: "hub" },
  { id: "production-ridge", label: "Production Ridge", x: 28, y: 22, type: "region" },
  { id: "agentic-loop", label: "Agentic Loop", x: 72, y: 25, type: "region" },
  { id: "migration-pass", label: "Migration Pass", x: 22, y: 75, type: "region" },
  { id: "research-basin", label: "Research Basin", x: 75, y: 75, type: "region" },
];

export const trails = [
  { from: "basecamp", to: "production-ridge" },
  { from: "basecamp", to: "agentic-loop" },
  { from: "basecamp", to: "migration-pass" },
  { from: "basecamp", to: "research-basin" },
  { from: "production-ridge", to: "agentic-loop" },
];
